### PR TITLE
First implementation of the Canvas node

### PR DESCRIPTION
**Pull request by HanSolo**

### CODE REVIEW

**Comment by tomsontom** [comment]
Looks fine but why did you move NSVGRegion to xlayout, was there a specific reason todo so?

**Comment by HanSolo** [comment]
if I compile it with tsc I get an error like „a class cannot be build before it‘s super class“ maybe my TS version is outdated. Also saw that ES2016 should work as compile target which does not work for me.  Will check my installation, feel free to change back.

**Comment by HanSolo** [comment]
Ok...just saw that my typescript version is indeed outdated...will update and fix it

**Comment by HanSolo** [comment]
works now :)

**Pull request merged**
